import os

import openai
from openai import OpenAI
import streamlit as st

os.environ["OPENAI_API_KEY"] = st.secrets["OPENAI_API_KEY"]

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)

st.title('🎁 제품 홍보 포스터 생성기')
keyword = st.text_input("키워드를 입력하세요.")

if st.button('생성하기🔥'):
    with st.spinner('생성 중입니다.'):
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": "입력 받은 키워드에 대한 150자 이내의 솔깃한 제품 홍보 문구를 작성해줘.",
                },
                {
                    "role": "user",
                    "content": keyword,
                }

            ],
            model="gpt-4",
        )
        result=chat_completion.choices[0].message.content
        st.write(result)

    with st.spinner('이미지 생성 중입니다...'):
        try:
            image_response = client.images.generate(
                model="dall-e-3",
                prompt=f"{keyword}에 대한 고품질 제품 홍보 이미지를 생성해주세요.",
                n=1,
                size="1024x1024",
            )
            image_url = image_response.data[0].url
            st.subheader("생성된 이미지:")
            st.image(image_url, caption="Generated by DALL·E", use_column_width=True)
        except Exception as e:
            st.error(f"이미지 생성 중 오류가 발생했습니다: {e}")